import os
import requests
import yt_dlp
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes, CallbackQueryHandler

BOT_TOKEN = os.getenv("BOT_TOKEN")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# Custom Branding Details
BOT_NAME = "MediaLyrics AI Pro"
BOT_OWNER = "@AmeerAlam"  # Aapna username ya Telegram channel tag yahan daalein

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    welcome_msg = (
        f"✨ **Welcome to {BOT_NAME}!** ✨\n\n"
        "Main aapke bhejey hue video se poora **Speech / Lyrics** extract karke de sakta hoon.\n\n"
        "🌐 **Supported Platforms:**\n"
        "• 📘 Facebook Videos & Reels\n"
        "• 🔴 YouTube Videos & Shorts\n"
        "• 📸 Instagram Reels & Posts\n\n"
        "📌 **Kaise use karein?**\n"
        "Bas kisi bhi video ka link niche chat me send karein!"
    )
    keyboard = [
        [InlineKeyboardButton("👨‍💻 Developer", url="https://t.me/AmeerAlam"), InlineKeyboardButton("📢 Updates Channel", url="https://t.me/AmeerAlam")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(welcome_msg, parse_mode="Markdown", reply_markup=reply_markup)

async def process_video(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text.strip()
    
    # Supported domains check
    valid_platforms = ["facebook.com", "fb.watch", "youtube.com", "youtu.be", "instagram.com"]
    if not any(domain in url for domain in valid_platforms):
        await update.message.reply_text("⚠️ **Invalid Link!**\nKripya Facebook, YouTube, ya Instagram ka valid video link bhejein.")
        return

    status_msg = await update.message.reply_text("⚡ **[1/3] Video Processing Started...**\nAudio extract kiya ja raha hai, kripya intezar karein.")
    audio_file = f"audio_{update.message.message_id}.mp3"

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': f'audio_{update.message.message_id}',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '128',
        }],
        'quiet': True,
        'no_warnings': True
    }

    try:
        # Step A: Audio Extraction
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])

        await status_msg.edit_text("🎙️ **[2/3] Audio Extracted!**\nAI Whisper Engine lyrics generate kar raha hai...")

        # Step B: AI Transcription Call
        with open(audio_file, "rb") as file:
            response = requests.post(
                "https://api.groq.com/openai/v1/audio/transcriptions",
                headers={"Authorization": f"Bearer {GROQ_API_KEY}"},
                files={"file": (audio_file, file, "audio/mp3")},
                data={"model": "whisper-large-v3"}
            )

        if os.path.exists(audio_file):
            os.remove(audio_file)

        result = response.json()
        extracted_text = result.get("text", "").strip()

        # Step C: Stylish Output Presentation
        if extracted_text:
            await status_msg.delete()
            
            header = f"🎬 **EXTRACTED LYRICS / SPEECH**\n"
            header += f"━━━━━━━━━━━━━━━━━━━━━━\n\n"
            footer = f"\n\n━━━━━━━━━━━━━━━━━━━━━━\n"
            footer += f"🤖 **Generated by:** {BOT_NAME}\n"
            footer += f"👑 **Owner:** {BOT_OWNER}"

            full_response = header + extracted_text + footer

            keyboard = [
                [InlineKeyboardButton("🔄 Extract Another Video", switch_inline_query_current_chat="")]
            ]
            reply_markup = InlineKeyboardMarkup(keyboard)

            if len(full_response) > 4000:
                for i in range(0, len(extracted_text), 3500):
                    part = extracted_text[i:i+3500]
                    await update.message.reply_text(f"📝 **Part:**\n\n{part}")
                await update.message.reply_text(footer, reply_markup=reply_markup)
            else:
                await update.message.reply_text(full_response, parse_mode="Markdown", reply_markup=reply_markup)
        else:
            await status_msg.edit_text("❌ **No Speech Found!**\nIs video me koi clear lyrics ya voice over nahi mila.")

    except Exception as e:
        await status_msg.edit_text(f"❌ **Error Occurred:**\n`{str(e)}`")
        if os.path.exists(audio_file):
            os.remove(audio_file)

def main():
    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, process_video))
    app.run_polling()

if __name__ == "__main__":
    main()
